### ISSUE TITLE
Thanks so much for doing this!

### ISSUE THREAD

**Issue by zacgoodwin** [Someone0nEarth/excalidraw-self-hosted#2]
I've adopted your YAML to use with Cosmos Cloud but I am running into an issue where I Excalidraw doesn't seem to be able to connect to the storage. I also try manually hitting the storage endpoints https://storage.local/api/v2/scenes/ and it just returns: 

{"statusCode":404,"message":"Cannot GET /api/v2/scenes/","error":"Not Found"}

Any suggestions on where to start troubleshooting?

**Comment by Someone0nEarth** [comment]
Hi, I don't think you can use any other storage solution than Firebase (as provided by the excalidraw developer) or the custom http storage (which is used in this repo solution).
